version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: monthly
  commit-message:
    prefix: dependencies
  reviewers:
    - "XoseRamon"
    - "m-timmermann"
    - "dwebel"
    - "iavorJ"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
  reviewers:
    - "XoseRamon"
    - "rwenz3l"